-- BigQuery Schema Definition for Field Journal

-- ==========================================
-- TABLE 1: raw_ebird_observations
-- ==========================================
-- This is an append-only table designed for resilience against eBird schema changes.
-- We strictly maintain native eBird semantic field names here.
-- We extract only the critical fields for partitioning and clustering, and dump 
-- the rest of the payload into a native JSON column.

CREATE TABLE IF NOT EXISTS `longhorizon.field_journal.raw_ebird_observations_ledger` (
    -- eBird Native Fields
    obs_id STRING NOT NULL,                   -- Generated composite ID: {subId}_{speciesCode}
    payload_hash STRING NOT NULL,             -- SHA256 hash of the raw JSON payload (for change detection)
    subId STRING NOT NULL,                    -- eBird checklist ID (e.g., 'S332768388')
    locId STRING NOT NULL,                    -- eBird specific hotspot ID (e.g., 'L619821')
    speciesCode STRING NOT NULL,              -- eBird species code (e.g., 'brant')
    comName STRING,                           -- Common name (e.g., 'Brant')
    obsDt DATETIME NOT NULL,                  -- Date/time of observation
    howMany INT64,                            -- Number of individuals seen
    
    -- Ingestion Metadata (System Time)
    ingestedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    
    -- The Catch-All (Resiliency Strategy)
    rawPayload JSON NOT NULL                  -- The full JSON object returned by eBird
)
PARTITION BY DATE(ingestedAt)                 -- Partition by system time for ledger analysis
CLUSTER BY obs_id, obsDt;                     -- Optimized for point-in-time reconstructions

-- ==========================================
-- VIEW 1.5: current_ebird_observations
-- ==========================================
-- The "Latest State" view. This is what the LLM agent will query 99% of the time.
-- It resolves the ledger down to the most recent version of every observation.

CREATE OR REPLACE VIEW `longhorizon.field_journal.current_ebird_observations` AS
SELECT * EXCEPT(row_num)
FROM (
    SELECT 
        *,
        ROW_NUMBER() OVER (PARTITION BY obs_id ORDER BY ingestedAt DESC) as row_num
    FROM `longhorizon.field_journal.raw_ebird_observations_ledger`
)
WHERE row_num = 1;

-- ==========================================
-- TABLE 2: target_locations
-- ==========================================
-- This table defines our semantic layer, mapping our business logic 
-- (e.g. "Sanctuaries" or "Reporting Groups") to the source-specific eBird hotspots.

CREATE TABLE IF NOT EXISTS `longhorizon.field_journal.target_locations` (
    location_group_id STRING NOT NULL,        -- Our semantic ID (e.g., 'fishers_island')
    display_name STRING NOT NULL,             -- e.g., 'Fishers Island Conservancy'
    ebird_locIds ARRAY<STRING>,               -- Array of eBird hotspot IDs: ['L3562597', 'L123456']
    is_active BOOL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- ==========================================
-- TABLE 3: generated_content
-- ==========================================
-- Stores the final output generated by the LLM agent.

CREATE TABLE IF NOT EXISTS `longhorizon.field_journal.generated_content` (
    post_id STRING NOT NULL,                  -- Unique ID for the post
    location_group_id STRING NOT NULL,        -- Links back to our semantic location group
    target_date DATE NOT NULL,                -- The primary date this post represents
    
    -- Content
    theme STRING,                             -- e.g., 'field_journal', 'conservation_lab'
    markdown_content STRING NOT NULL,         -- The LLM-generated narrative
    json_metadata JSON,                       -- Any extracted insights or structured UI data
    
    status STRING DEFAULT 'draft',            -- draft, published, archived
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
PARTITION BY target_date
CLUSTER BY location_group_id;
